name: Multi-Platform Build
on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake
          cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-Old-Exe
          path: build/Release/old.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhidapi-dev
      - name: Build
        run: |
          cmake -B build 
          cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: Linux-Binary
          path: build/Controller_Linux

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          cmake -B build
          cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: MacOS-Binary
          path: build/Controller_MacOS
